environment:
  matrix:
  
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      configuration: Debug
      output_name_postfix: Debug
      arch: x64
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      configuration: Debug
      output_name_postfix: Debug
      arch: Win32
    
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      configuration: Release
      arch: x64
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      configuration: Release
      arch: Win32
      
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Debug
      output_name_postfix: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Debug
      output_name_postfix: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Release
      
    
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      configuration: Debug
      output_name_postfix: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      configuration: Debug
      output_name_postfix: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      configuration: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      configuration: Release
      
  
install:
  - git submodule update --init --recursive
  - cmake --version
  
build_script:
  - mkdir Build
  - cd Build
  - echo %configuration%
  - cmake -G "%generator%" -A "%arch%" "-DCMAKE_BUILD_TYPE=%configuration%" ..
  - cmake --build . --config %configuration%
   
after_build:
   - cd ../Bin
   - CurseCoreTest%output_name_postfix%.exe