language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - clang-3.9
      - lcov
      - valgrind
    update: true
  
matrix:
  include:
  
    - os: linux
      compiler: gcc
      env:
        - CONFIG=Release
        
    - os: linux
      compiler: gcc
      env:
        - CONFIG=Debug OUTPUT_NAME_POSTFIX=Debug
        
    - os: linux
      compiler: clang
      env:
        - CONFIG=Release
        
    - os: linux
      compiler: clang
      env:
        - CONFIG=Debug OUTPUT_NAME_POSTFIX=Debug
  
script:
  # Checks
  - g++ --version
  - gcc --version
  - gcov --version
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=${CONFIG} ..
  - cmake --build . --config ${CONFIG}
  # Run test
  - cd ../bin/test
  - valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./CurseCoreTest${OUTPUT_NAME_POSTFIX}
  - cd ../../build
  
after_success:
  #- lcov --directory ./CMakeFiles/CurseCoreTest.dir --capture --output-file coverage.info
  #- lcov --extract coverage.info '*/CurseCoreTests.hpp' '*/CurseCoreTests.cpp' --output-file coverage.info
  #- lcov --list coverage.info
  #- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
