language: cpp

dist: trusty
  
matrix:
  include:
  
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - lcov
      env:
        - CONFIG=RELEASE
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - lcov
      env:
        - CONFIG=Debug OUTPUT_NAME_POSTFIX=Debug
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - lcov
      env:
        - CONFIG=RELEASE
        - MATRIX_EVAL="CC=clang-6.0 CXX=clang++-6.0"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - lcov
      env:
        - CONFIG=Debug OUTPUT_NAME_POSTFIX=Debug
        - MATRIX_EVAL="CC=clang-6.0 CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}" 
  
script:
  # Checks
  - g++ --version
  - gcc --version
  - gcov --version
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=${CONFIG} ..
  - cmake --build . --config ${CONFIG}
  # Run test
  - cd ../bin/test
  - valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./CurseCoreTest${OUTPUT_NAME_POSTFIX}
  - cd ../../build
  
after_success:
  #- lcov --directory ./CMakeFiles/CurseCoreTest.dir --capture --output-file coverage.info
  #- lcov --extract coverage.info '*/CurseCoreTests.hpp' '*/CurseCoreTests.cpp' --output-file coverage.info
  #- lcov --list coverage.info
  #- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
